name: Execution des tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests execution
        uses: matt-ball/newman-action@master
        with:
          collection: collection.json
