name: Execution des tests avec npm

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --global newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: newman run newman run "https://api.getpostman.com/collections/92eb399c-cb83-4ca8-a02c-fcdd8e244716?apikey=${{ secrets.POSTMAN_API_KEY}}" -r cli,junit,htmlextra

      - name: Publish JUnit reports
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API tests # Name of the check run which will be created
          path: newman/*.xml # Path to test results
          reporter: java-junit
      - name: Publier le rapport HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-${{ github.run_id }}
          path: newman/*.html
